### ISSUE TITLE
Does not work inside template

### ISSUE THREAD

**Issue by Stefdv** [kcmr/code-sample#2]
This has the same problem as Polymers demo-snippet...
It doesn't work inside another template ( aka inside a custom element )

**Comment by kcmr** [comment]
Sorry for the late response.

Yes, the issue is the same [described here](https://github.com/Polymer/polymer/issues/3177).
I'm looking for a solution right now, but as a quick fix, you can add the attribute `preserve-content` to the inner `template`.

Example:
```
<code-sample>
  <template preserve-content>
    .benton-sans-light { font-weight: 300; }
  </template>
</code-sample>
```
