### ISSUE TITLE
Way to include different highlight.js (with more/different languages to highlight)?

### ISSUE THREAD

**Issue by naibaf0** [kcmr/code-sample#9]
Is there a way, or could there be added a way to import different variants of the `highlight.pack.js` file? The one included only supports the standard choice of languages I think and there are many more to choose from.

**Comment by naibaf0** [comment]
Never mind, importing highlight.pack.js in a script tag where ever `code-sample` is used does exactly what I want. Thanks and great element!

**Comment by kcmr** [comment]
FYI. I’m going to include more languages in a future release using polymer 3.
